### ISSUE TITLE
Remove writable alias

### ISSUE THREAD

**Issue by ebeloded** [joshnuss/svelte-persisted-store#214]
First off: thank you! Great svelte utility. I use it all the time.

I suggest removing the `writable` alias to avoid the auto-import suggestion:

![2023-11-16 at 12 33 30](https://github.com/joshnuss/svelte-persisted-store/assets/5859177/24bc4d83-b0a2-4a6f-b8a4-85c358f458de)

**Comment by bertmad3400** [comment]
This feature has already been deprecated (and your editor should warn you about that), and I would believe that @joshnuss would remove them in the near future when they conclude that it's no longer needed for backwards compatibility.

**Comment by ebeloded** [comment]
Yeah, there is a warning about deprecation, but it doesn't stop the editor from automatically importing `writable` from `svelte-persistent-store`.

**Comment by joshnuss** [comment]
Welcome @ebeloded,

As @bertmad3400 pointed out, it's a deprecated function, and marked with TypeScript's `@deprecated` annotation. It will be removed in the next major release.

So I think the issue is really with the language tool / editor you're using. It's prioritizing a deprecated function in their auto complete.

I'd consider opening an issue with them.
