### ISSUE TITLE
Svelte 5 support

### ISSUE THREAD

**Issue by danawoodman** [joshnuss/svelte-persisted-store#230]
I understand Svelte 5 is still a preview release, but I'd love to be able to use this store with it. I believe since Svelte 5 is backwards compatible it should just work adding v5 to the `peerDependencies` chain.

Could throw together a PR if interested

**Comment by joshnuss** [comment]
Hi Dana!

Yes, I'd like to fully support Svelte 5.

Ideally it should support Runes too. But in the meantime, updating `peerDependencies` is a start.

Since Svelte5 is a major update, I'd like to change a few things too.

- **Remove deprecations**: Importing using the old function name `writable` is still supported, but i'd like to remove that. ie `import { writable } from 'svelte-persisted-store`)
- **Consider switching to `devalue`** as the default serializer (instead of `JSON`). Because a common gotcha is using values like `undefined` and serialization doesn't work as expected.
- **Cookie support**: it would be nice if cookies could be supported too, but I need to decide on a solution that works with SSR and CSR. Maybe with Runes it will be easier?

**Comment by knd775** [comment]
> * **Consider switching to `devalue`** as the default serializer (instead of `JSON`). Because a common gotcha is using values like `undefined` and serialization doesn't work as expected.

The problem with this is that `devalue` is very picky and doesn't work with really common things like symbol keys on objects.

**Comment by joshnuss** [comment]
@knd775 I feel like the [features it provides](https://github.com/Rich-Harris/devalue#devalue) could be more useful than `Symbol` keys.

I'm suggesting this, because "try devalue" is a common solution to many support requests.

And keep in mind, JSON will continue to be supported. It just wouldn't be the default option anymore.

**Comment by danawoodman** [comment]
I'd vote a minor release with just the peerDep change so people can start using it, then follow up with these other things :)

**Comment by joshnuss** [comment]
@danawoodman agree. Feel free to open a PR

**Comment by webJose** [comment]
Pardon the interruption.  Why people serialize `undefined`?  In my mind, if the store's value is `undefined`, it would mean it needs to be deleted.  Serializing and deserializing it seems like a major waste of effort in my ignorant mind.  If the store gets set to `undefined`, I would expect the store to delete from local storage.  Anything I'm missing?

**Comment by danawoodman** [comment]
@joshnuss pr up #233 !

**Comment by joshnuss** [comment]
@danawoodman I'll take a look

@webJose I agree with you, for nested attributes in an object. The problem is that if you set the root value to `undefined`, for some reason `localStorage.setItem()` saves it as a string `"undefined"`.

```javascript
> localStorage.setItem('mykey', undefined)
> localStorage.getItem('mykey')
"undefined"
```

But it's not just undefined-handling that makes `devalue` useful. It also supports `Date`, `Set`, `Map`, 'BigInt', circular objects, `Infinity`, `NaN`
